### ISSUE TITLE
CSS: ordered list start left of container div

### ISSUE THREAD

**Issue by igalic** [Brainsware/sealas-site#15]
unlike their unordered cousins:

![spectacle k22156](https://user-images.githubusercontent.com/497249/31856011-5a45a5cc-b6b7-11e7-856b-4ae06d01b1e7.png)

ordered lists are leaving our container `div` to the left:

![spectacle b22156](https://user-images.githubusercontent.com/497249/31856015-8518707c-b6b7-11e7-80b5-d034d3c50a01.png)

**Comment by DKhalil** [comment]
Fixed

**Comment by igalic** [comment]
plz ref issues in your commits next time 💜
